---
version: '3.5'

services:
  build-cache:
    image: gradle/build-cache-node:latest
    networks:
      - gradle
    ports:
      - "8080:80"
#      - "8443:443"
    volumes:
      - build-cache-data:/data
    deploy:
#      placement:
#        constraints:
#          - node.role==worker
      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 10s
      restart_policy:
        condition: any

networks:
  gradle:
#    external: true

volumes:
  build-cache-data:
    external: true
